const actionstypes = {
  FETCH_PATIENTS_START: 'HMS/PATIENTS/FETCH_START',
  FETCH_PATIENTS_SUCCESS: 'HMS/PATIENTS/FETCH_SUCCESS',
  FETCH_PATIENTS_ERROR: 'HMS/PATIENTS/FETCH_ERROR',
  UPDATE_PATIENT_VITALS: 'HMS/PATIENTS/UPDATE_VITALS',
};

export default actionstypes;
